# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The submersible project
author:
  name: Ray Anchordoquy
  email: ranchordo@gmail.com
description: A project to build a hydro-acoustically-controlled underwater robot.
baseurl: "/submersible-project" # the subpath of your site, e.g. /blog
url: "https://ranchordo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ranchordo
github_username:  ranchordo

# Build settings
markdown: kramdown
remote_theme: jekyll/minima

show_excerpts: false
header_pages:
  - gallery.md
plugins:
  - jekyll-feed
  - jekyll-remote-theme
minima:
  skin: dark
  social_links:
    - {platform: github, user_url: "https://github.com/ranchordo"}
    - {platform: youtube, user_url: "https://youtube.com/@ranchordo"}
